'use strict';

/**
 * src/models/category.model.js
 *
 * Category schema using the Materialized Path pattern.
 *
 * ── Why Materialized Path? ────────────────────────────────────────────────────
 * We need to:
 *   (a) Fetch all descendants of a category (for product filtering)
 *   (b) Render the full hierarchy as a tree
 *   (c) Prevent circular references
 *
 * The `ancestors` array stores all ancestor IDs from root → direct parent.
 *
 * Example:
 *   Electronics  → parent: null,           ancestors: []
 *   Computers    → parent: Electronics,    ancestors: [Electronics._id]
 *   Laptops      → parent: Computers,      ancestors: [Electronics._id, Computers._id]
 *   Gaming       → parent: Laptops,        ancestors: [Electronics._id, Computers._id, Laptops._id]
 *
 * To find ALL descendants of Electronics (single indexed query):
 *   { $or: [{ _id: electronicsId }, { ancestors: electronicsId }] }
 *
 * To detect circular reference when reparenting C → P:
 *   Check if C._id appears in P.ancestors (or P._id === C._id)
 */

const mongoose = require('mongoose');

const categorySchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Category name is required'],
      trim: true,
      minlength: [2, 'Category name must be at least 2 characters'],
      maxlength: [100, 'Category name must be at most 100 characters'],
    },

    slug: {
      type: String,
      unique: true,
      lowercase: true,
      trim: true,
      // Generated by service before save — not set by the client
    },

    description: {
      type: String,
      trim: true,
      maxlength: [500, 'Description must be at most 500 characters'],
      default: '',
    },

    // Self-referencing parent — null means root category
    parent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      default: null,
    },

    // Full ancestor chain from root to direct parent (ordered).
    // Maintained by the service layer on create and reparent.
    ancestors: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Category',
      },
    ],
  },
  {
    timestamps: true,
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
// slug is already indexed by unique:true.
// Index on parent for fast child-lookup queries.
categorySchema.index({ parent: 1 });
// Index on ancestors for fast descendant queries (product filtering).
categorySchema.index({ ancestors: 1 });
// Text index on name for search.
categorySchema.index({ name: 'text' });

// ─── Virtual: depth ───────────────────────────────────────────────────────────
// Convenience: depth in tree = number of ancestors.
categorySchema.virtual('depth').get(function () {
  return Array.isArray(this.ancestors) ? this.ancestors.length : undefined;
});

// ─── toJSON cleanup ───────────────────────────────────────────────────────────
categorySchema.set('toJSON', {
  virtuals: true,
  transform(_doc, ret) {
    delete ret.__v;
    delete ret.id; // remove duplicate of _id added by virtuals
    return ret;
  },
});

const Category = mongoose.model('Category', categorySchema);

module.exports = Category;
